#!/usr/bin/env bash
# shellcheck disable=SC2086
# Script that displays information about domain and subdomains.

domain_info() {
    DOMAIN=$1
    SUBDOMAIN=$2
    RECORD=$(dig +noall +answer $SUBDOMAIN.$DOMAIN | awk '{ print $4 }')
    IP=$(dig +noall +answer $SUBDOMAIN.$DOMAIN | awk '{ print $5 }')
    echo "The subdomain $SUBDOMAIN is a $RECORD record and points to $IP"
}

if [ "$#" == 1 ]
then
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    domain_info "$1" "$2"
fi
