#!/usr/bin/env bash
# transfers a file to a client from a server

if [[ "$#" -ne 5 ]];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY LOCAL_FILE"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$3"@"$2":"$1"
fi
