#!/usr/bin/env bash
# Configure a custom nginx response header
apt-get update
apt-get -y install nginx
HOSTNAME=$(cat /etc/hostname)
sed -i "/listen \[::\]:80 default_server;/a \\\n\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-enabled/default
service nginx restart
