#!/usr/bin/env bash
# Configure a custom 404 page
apt-get update
apt-get -y install nginx
sed -i "/listen \[::\]:80 default_server;/a \\n\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default
service nginx restart
