#!/usr/bin/env bash
# Install and configure HAproxy load balancer
apt -y update
apt-get install -y haproxy

echo "frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 2760-web-01 34.75.248.214:80 check
        server 2760-web-02 35.229.37.122:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
