#!/usr/bin/env bash
#Script that displays "To infinity and beyond" indefinitely.
trap 'echo "I am invincible!!!"' SIGTERM
i=0
while [ $i -le 1 ]; 
do
    echo "To infinity and beyond"
    sleep 2
done