#!/usr/bin/env bash
#Script that displays "Holberton School" 10 times using while loop, but for the 9th iteration, displays Holberton School and then Hi.
i=1
while [ $i -le 10 ]; 
do 
    echo "Holberton School" 
    if [ $i -eq 9 ];
    then
        echo "Hi"
    fi
    ((i++))
done