#!/usr/bin/env bash
#Script that displays "Holberton School" 10 times using while loop. Display "bad luck" for the 4th, and display "good luck" for the 8th.
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++)) 
done