#!/usr/bin/env bash
#Script that displays "Holberton School" 10 times using while loop.
hour=0
while [ $hour -le 12 ]; 
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo $minute
        ((minute++))
    done
    ((hour++))
done