#!/usr/bin/env bash
#Script that gives you information about the holbertonschool file.
file="holbertonschool"
if [ -e "holbertonschool" ];
then
    echo "$file file exists"

    if [ -f $file ]
    then
        echo "$file is a regular file"
    fi

    if [ -s $file ]
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
else
    echo "$file file does not exist"
fi