#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts hosts_tmp
sed -i "s/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' hosts_tmp
cp -f hosts_tmp /etc/hosts